start = root 
root = element root {topPage, group*}
topPage = element topPage {company, title*, subheading?}
group = element group {num, bold,image*, para?}
num = attribute num {xsd:integer}
company = element company {text}
title = element title {text}
subheading = element subheading {text}
bold = element bold {text}
image = element image {src, text}
src = attribute src {"ny_sun_death-and-madness.png" | "ny_sun_one-still.png" | "ny_sun_pumps.png" | "ny_sun_eleven.png" | "ny_sun_bibles.png" | "ny_sun_quiet-sea.png"}
para = element para {text}
